name: Build
on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Set git identity
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"

      - name: Apply patches
        run: ./gradlew applyPatches --no-daemon

      - name: Build reobfuscated paperclip jar
        run: ./gradlew createReobfPaperclipJar --no-daemon

      - name: Upload reobfuscated paperclip jar
        uses: actions/upload-artifact@v3
        with:
          name: CloudPlane-Artifacts
          path: build/libs/CloudPlane-paperclip-*
          if-no-files-found: error
